name: Deploy to EC2 (local build)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Move build to ROOT dir
        run: |
          rm -rf /home/$USER/ROOT/.next /home/$USER/ROOT/public
          cp -r .next public /home/$USER/ROOT/

      - name: Restart PM2 app
        run: |
          pm2 restart pw